### ISSUE TITLE
Unexpected behavior doing nested iteration on a SelectQuery

### ISSUE THREAD

**Issue by martinburch** [coleifer/peewee#682] opened 2015-08-04 17:36 UTC
Hi, I wanted to bring an issue to your attention: nested iteration of SelectQuery results doesn't work as expected. You can see an example, and a workaround, on my StackOverflow question:
http://stackoverflow.com/questions/31815235/python-peewee-iterate-over-selectquery

Is there an iterator that needs to be reset somewhere? Maybe at the end of the inner loop?

Thanks!

**Comment by coleifer** [comment] 2015-08-05 16:00
Here is a description of the problem:

```python
# create 5 users, named user0-user4
query = User.select()
for o in query:
    print 'o ->', o.username
    for i in query:
        print '    i ->', i.username
```

This will print:

```
o -> u0
    i -> u0
    i -> u1
    i -> u2
    i -> u3
    i -> u4
```

**Comment by coleifer** [comment] 2015-08-06 20:56
So when you iterate over a `SelectQuery` it creates a `QueryResultWrapper` which allows for efficient iteration and indexing. The problem is that the iterator is stateful.

The workaround I'd suggest is just to coerce to a `list` beforehand.

I'll see about a better fix.

**Comment by coleifer** [comment] 2015-09-04 03:08
This should now be fixed in master.

**Comment by martinburch** [comment] 2015-09-04 03:09
Great, thanks!

**Closed by coleifer** 2015-09-04 03:08 UTC
